### ISSUE TITLE
Suport LiveView-based interactions?

### ISSUE THREAD

**Issue by dalerka** [woylie/flop_phoenix#10]
Hey, thanks for sharing the neat Flop libraries! 
Would it be possible for Phoenix helpers to work with LiveView instead of HTTP?

**Comment by woylie** [comment]
Hey @dalerka, that would be a nice addition, but I haven't looked into it yet. If you want to work on it yourself, pull requests are welcome. Otherwise I hope I can find some time to work on it myself.
