### ISSUE TITLE
pagination: display first/last links

### ISSUE THREAD

**Issue by woylie** [woylie/flop_phoenix#12]
The pagination helper should always display links to the first and last page, even if the number of page links is limited with the ellipsis option.

**Comment by jesselathamdev** [comment]
Looks good @woylie!

**Comment by jesselathamdev** [comment]
@woylie sorry for coming back to this so late in the game, but could you give me a hand with this one - in the non-liveview case I'm not seeing the first and last links appear? in the vanilla installation with no customizations applied (just using `import Flop.Phoenix` in web.ex I only see the following:

<img width="304" alt="Screen Shot 2021-04-10 at 9 58 51 AM" src="https://user-images.githubusercontent.com/1715131/114278172-65d4c180-99e3-11eb-9161-cfb2ca1ddc3f.png">

Thoughts?

**Comment by woylie** [comment]
I think what you expected and what I implemented are two different things. I changed the implementation, so that the link to the first page (`1`) and to the last page (`34`) are always displayed, even if the number of page links is limited. So if you use the `ellipsis` option, you would see something like `previous next 1 ... 21 22 23 ... 60`. Previously, you would only have seen `previous next ... 21 22 23 ...`.

![image](https://user-images.githubusercontent.com/13847569/114329083-774fd200-9b79-11eb-9424-63140960e0a0.png)

The count helper is a bit difficult, since it would have to work with different languages. It's easy to translate `next` and `previous` as single words. But `Displaying 1 to 15 of 505 items` needs to consider the grammar of the language. It might look entirely different, e.g. `505件中1～15件を表示`. You would have to support passing a format string. But that also doesn't help you a lot if your site is multilingual - you'd have to take care yourself of passing the correct format string depending on the current language. Also, maybe you don't want to display `1 to 15 of 505`, but just `15 of 505`. So then you can better add a function like this to your view helpers:

```
def result_count(%Flop.Meta{current_offset: current_offset, next_offset: next_offset, total_count: total}) do
  ~e"""
  <p><%= gettext("Displaying %{first} to %{last} of %{total} results", first: current_offset + 1, last: next_offset, total: total) %></p>
  """
end
```
