### ISSUE TITLE
Make rows clickable

### ISSUE THREAD

**Issue by nathanmalishev** [woylie/flop_phoenix#131]
**Is your feature request related to a problem? Please describe.**
I would like to add an option to the table, to make each row easily clickable with the item available.

**Describe the solution you'd like**
Add extra attr to table

**Describe alternatives you've considered**
I've trade adding `phx-click` to each `col` but I couldn't quite get it working with the params as the `:let` didn't exist for the other attrs.

**Comment by woylie** [comment]
resolved in #132
