### ISSUE TITLE
Pagination: hide/disable limit

### ISSUE THREAD

**Issue by woylie** [woylie/flop_phoenix#14]
This issue has two parts:

1. `Flop.Schema` should allow to disable the limit parameter if a default limit is set.
2. `FlopPhoenix.pagination` should hide the limit/page_size parameters if limiting is disabled or the default limit is used.

See discussion in https://github.com/woylie/flop_phoenix/issues/8.

**Comment by jesse-iluminai** [comment]
Hi Mattias - have you given any other thoughts to this or how to remove the unnecessary params if we want to fix the page size?

**Comment by woylie** [comment]
This issue isn't very high on my priority list at the moment. With the latest changes, we'd have to update the `Flop.Phoenix.to_query/1` and/or `Flop.Phoenix.build_path/3` to accept an options list, which would allow us to pass the `:for` option and determine which values from meta.flop match the default values and can thereby be omitted. Also, we can remove `offset=0` and `page=1` in any case.

**Comment by woylie** [comment]
I made some changes in #28. I still need to test it in a real application. Please let me know whether this meets your requirements and whether you encounter any problems.

**Comment by woylie** [comment]
This change was merged, at least the hiding of default parameters. Disabling the limit altogether as mentioned in the first comment should be tracked in Flop, if needed.
