### ISSUE TITLE
Use stream resetting/bulk insert functionality

### ISSUE THREAD

**Issue by zolrath** [woylie/flop_phoenix#187]
The original live_view stream implementation did not have a way to reset the stream to clear it's elements when paginating.

Flop worked around this issue by using the [row number instead of the items ID](https://github.com/woylie/flop_phoenix/pull/176) and updating the stream items in place, but the upcoming version of streams [now has reset and bulk insert functionality](https://github.com/phoenixframework/phoenix_live_view/pull/2577).

**Describe the solution you'd like**
Use the streams reset to clear existing items when paginating instead of mutating existing rows for clarity. Additionally, a list of items can be passed in instead of iterating the insertion.

**Issues**
This new version of live_view hasn't been released just yet - this is primarily to track an eventual transition to the more logical APIs now that they exist.

**Comment by woylie** [comment]
Thanks, but there's nothing to do on the flop_phoenix site for this. The row number implementation is just an example implementation that's not part of the repo. The updated table component has everything needed to support streams, but the streams themselves have to be created and updated outside of the component. The table component does not handle its own state.
