### ISSUE TITLE
Add enum type to filter_fields

### ISSUE THREAD

**Issue by obsidienne** [woylie/flop_phoenix#190]
**Is your feature request related to a problem? Please describe.**
Hi, 
I use ecto Enum type a lot stored as string. In my form, I need to have a checkbox per possible value. 

**Describe the solution you'd like**

I would like an auto extract of an array of tuple with the enum value and if he's checked 

Something like the select example in the doc but automagically filled because it's an enum. 

**Describe alternatives you've considered**
Do it manually

Thanks

**Comment by woylie** [comment]
That's out of scope for flop_phoenix. The field configuration of the filter fields component only supports the `label`, `op` and `type`. Any other options will just be passed to the inner block, which is what happens with the `options` and `prompt` in the `select` example in the documentation.

If you want to automatically set the select options from an Ecto enum, you can define a function for that somewhere in your project like this:

```elixir
def enum_options(module, field) do
  module
  |> Ecto.Enum.values(field)
  |> Enum.map(fn v -> {v, v} end)
end
```

What the anonymous function looks like depends on your use case. You might want to humanize the value for display, or translate it with gettext.

Once you have defined that function, you can use it like this, assuming that your Ecto schema is defined in `MyApp.Pet` and the enum field is `:status`:

```elixir
fields={[
  age: [
    label: gettext("Status"),
    type: "select",
    prompt: "",
    options: enum_options(MyApp.Pet, :status)
  ]
]}
```
