### ISSUE TITLE
Allow disabling of sorting via column headers in Flop.Phoenix.Table

### ISSUE THREAD

**Issue by wodow** [woylie/flop_phoenix#195]
In some situations, it would be useful to disable sorting by columns.

This could be an option like those in https://hexdocs.pm/flop_phoenix/Flop.Phoenix.html#t:table_option/0 ?

**Comment by woylie** [comment]
Do you need to conditionally disabling sorting for all columns?

**Comment by wodow** [comment]
> Do you need to conditionally disable sorting for all columns? Any context?

That would still be a nice-to-have, but I now see one can implement that by e.g. `field={@allow_sortable && :field_name}` repeated over all fields.

**Comment by woylie** [comment]
> Could document to https://hexdocs.pm/flop_phoenix/readme.html#sortable-tables-and-pagination ?

I added some notes in #197.
