### ISSUE TITLE
Support conditionally styling table rows

### ISSUE THREAD

**Issue by wodow** [woylie/flop_phoenix#203]
It would be useful to be able to conditionally style rows in `Flop.Phoenix.table` based on the row's item.

For example, highlighting with a colour or striking-thru.

I'm not sure what a good API would be for this.

**Comment by wodow** [comment]
This would override the table option `:tbody_tr_attrs`.

**Comment by wodow** [comment]
Perhaps simplest: `Flop.Phoenix.table` gains a new attr `row_style` which expects a function of loose spec `row_style(any) :: string`.

**Comment by woylie** [comment]
Sorry for the late answer. I'm not sure about this yet, I'll have to think about the API. But there's a bunch of other stuff I want to get done first, so it could take a bit.

**Comment by woylie** [comment]
resolved in #229
