### ISSUE TITLE
Feature request: ability to statically declare `nulls_first` or `nulls_last` on (non-default) sortable table columns.

### ISSUE THREAD

**Issue by vanderhoop** [woylie/flop_phoenix#241]
**Is your feature request related to a problem? Please describe.**

My use case is a pagination table that can be sorted by specific columns that represent performance metrics. These metrics are nullable, and they do not represent the default sorting of the records. It's often useful to see the outliers for these metrics, but given they can be null, the user can be presented with pages and pages of blank metric values due to the standard `asc/desc` sorting.

At the moment, I can identify 2 ways of sorting a non-default sorting column using the `_nulls_{first,last}` qualifier:

1. use the `on_sort` assign to push a custom event using the `JS` module, and pattern match in the event handler to manipulate the `Flop.Meta` struct.
2. pattern match out the head of the `order_by` and `order_directions` lists that come through via params in the default `update-filters` event and manually manipulate the item from `order_directions` (if and only if it's one of my metrics).

Are there other ways that I'm missing?

**Describe the solution you'd like**

A table `col` can optionally declare, via assign, qualifiers for sorting direction. Something like:

```heex
<:col
  :let={navigation}
  label="CLS"
  field={:cls}
  sorting_qualifiers={[asc: :asc_nulls_first, desc: :desc_nulls_last]}
>
```

Where the default for this assign is `[asc: :asc, desc: :desc]` to maintain the current behavior.

My _guess_ is that most people would want `nulls_{first/last}` to be consistent regardless of `asc/desc`, but I'm wrong a lot, so providing a means to have different behavior for asc/desc might make sense.

**Additional context**
I'm happy to close this issue if there's already a low-cost solution in the lib. If that is the case, would love to see it documented (or raised more prominently in the table documentation if I missed it 😅).

**Comment by woylie** [comment]
To stay with the current naming, and to shorten the syntax a bit, maybe this is an option:

```elixir
<:col directions={{:asc_nulls_first, :desc_nulls_first}}
```

Default would be `{:asc, :desc}`. We'd also have to update `Flop.push_order/2` for this. Maybe it can receive an optional third `opts` argument, so that you can just pass on the `directions` attribute: `Flop.push_order(%Flop{}, :name, directions: {:asc_nulls_first, :desc_nulls_first}).`

The best workaround is probably the way via `JS.push`.

I'm open to a PR.

**Comment by vanderhoop** [comment]
Good call on the concision and naming. I'll poke around with push_order and see if I can cook this up.
