### ISSUE TITLE
Improve compatibility with Tailwind

### ISSUE THREAD

**Issue by MMore** [woylie/flop_phoenix#26]
**Is your feature request related to a problem? Please describe.**
Tailwind becomes more and more popular and it does not rely on predefined classes which is used in every and each table. With Liveview we start encapsulating styled components. In my specific case, when I am using `Flop.Phoenix.pagination` I have two issues:

1. I can't adjust the css class when it's the current page (fixed to`is-current`
2. I can't change the order of `previous_link`, `page_links` and `next_link`. For instance I'd like to have the `previous_link` before the `page_links` and the `next_link` at the end.

**Describe the solution you'd like**
The first issue could be fixed with a further customization option. The second issue by allowing to override the content of the `pagination` function.

**Describe alternatives you've considered**
For the moment I am basically overriding the `Flop.Phoenix.Pagination` module which isn't nice.

**Comment by woylie** [comment]
Thanks for your feature request. I added the option `current_link_attrs` in #27. This option is not merged into `pagination_link_attrs`, which means you'll need to duplicate any shared classes. For the default classes, this would mean:

```elixir
[
  pagination_link_attrs: [class: "pagination-link"],
  current_link_attrs: [class: "pagination_link is_current"]
]
```

The `pagination_link_aria_label` option is applied to both non-current and current links.

As for 2, I'm using flex box with the `order` property to bring the elements into the order I need.

In CSS with the default classes:

```css
.pagination {
  display: flex;

  .pagination-list {
    order: 2;
  }

  .pagination-previous {
    order: 1;
  }

  .pagination-next {
    order: 3;
  }
}
```

Or with Tailwind classes:

```elixir
opts = [
  wrapper_attrs: [class: "flex"],
  pagination_list_attrs: [class: "order-2"],
  previous_link_attrs: [class: "order-1"],
  next_link_attrs: [class: "order-3"]
]
```

Would this solution work for you?

**Comment by MMore** [comment]
Whoa, that was fast @woylie! And indeed your proposed solution works for me, thanks a lot! Also for this nice library which will be a shining star soon. There are some pagination libraries but I feel you really built a great package together with filtering and sorting. And it allows enough customization. Thank you!
