### ISSUE TITLE
Overriding attrs for table heading

### ISSUE THREAD

**Issue by damir** [woylie/flop_phoenix#263]
Hi Woylie,

I can override `tbody_td_attrs` to align some numbers to the right by passing `attrs={[class: "text-right ..."]}` to `:col` but there is no option to do the same with `thead_th_attrs`.

I also tried `attrs={[align: "right"]}`, it works for `td` but not for `th`.

**Comment by woylie** [comment]
Right, that's not supported at the moment. Do you have a proposal? I think we need to be able to override the th and td attributes separately. That would probably mean an additional `th_attrs` attribute on the `:col` slot. What do you think?

**Comment by damir** [comment]
Yes, `attrs` could be renamed to `td_attrs` since it controls `td`, and `th_attrs` could do the same for `th`. Or maybe use existing names instead - `tbody_td_attrs` and `thead_th_attrs`?

**Comment by dsrees** [comment]
I took a stab at this in #265 and also included overrides for the `th_wrapper_attrs` that are applied to the `span` for sortable headers.

An additional feature that I am looking into (that I believe is also related to these `th` changes) is providing custom icons for the `arrow/1` component. For example, we want to show the Heroicon `bars-arrow-down` or `bars-arrow-up` based on the sort order. I haven't however come up with a proposal for _how_ this could be done yet.

**Comment by dsrees** [comment]
> Or maybe use existing names instead - `tbody_td_attrs` and `thead_th_attrs`?

After also providing overrides for `th_wrapper_attrs`, I think this actually makes the most sense. I will update my PR to reflect this
