### ISSUE TITLE
filter_form example with fields

### ISSUE THREAD

**Issue by ghenry** [woylie/flop_phoenix#291]
Hi,

First, thanks for this project! Love it!

I was just cleaning up some CI (`mix compile --warnings-as-errors`) and see:

`warning: undefined attribute "fields" for component` as I'm using the example from the docs:

```
<.filter_form
  fields={[:name, :email]}
  meta={@meta}
  id="user-filter-form"
/>
```

I don't think `fields` is an attr on your example, right?

Thanks.

**Comment by woylie** [comment]
Thanks! You're right, the example also hard-coded the fields. I just merged a fix.

**Comment by ghenry** [comment]
Ah, sorry. I should have done a PR for you. Thanks!
