### ISSUE TITLE
Filtering by date

### ISSUE THREAD

**Issue by ghenry** [woylie/flop_phoenix#293]
Hi all,

I have a filterable field (which correctly renders a nice data picker):

`field :customer_request_date, :utc_datetime`

and am searching like so:

```
      <.filter_form
        fields={[
          number: [
            op: :ilike_and,
            type: "number"
          ],
          rt_ticket_ref: [
            op: :ilike_and,
            type: "number",
            label: "Ticket"
          ],
          status: [
            op: :ilike_and,
            type: "text",
            label: "Status"
          ],
          requested_by_email: [
            op: :ilike_and,
            type: "text",
            label: "Requested by"
          ],
          customer_request_date: [
            op: :>=,
            type: "date",
            label: "Acceptance date on or after"
          ]
        ]}
        meta={@meta}
        id="user-filter-form"
      />
```

but getting this:

```
[error] Error: %Flop.Meta{backend: nil, current_offset: nil, current_page: nil, end_cursor: nil, next_offset: nil, next_page: nil, page_size: nil, previous_offset: nil, previous_page: nil, schema: ResiSwitch.NumberPorting.Porting, start_cursor: nil, total_count: nil, total_pages: nil, errors: [filters: [[], [], [], [], [value: [{"is invalid", []}]]]], flop: %Flop{after: nil, before: nil, first: nil, last: nil, limit: nil, offset: nil, order_by: nil, order_directions: nil, page: nil, page_size: nil, decoded_cursor: nil, filters: []}, has_next_page?: false, has_previous_page?: false, opts: [for: ResiSwitch.NumberPorting.Porting], params: %{"filters" => [%{"field" => "number", "op" => "ilike_and", "value" => "122490"}, %{"field" => "rt_ticket_ref", "op" => "ilike_and", "value" => ""}, %{"field" => "status", "op" => "ilike_and", "value" => ""}, %{"field" => "requested_by_email", "op" => "ilike_and", "value" => ""}, %{"field" => "customer_request_date", "op" => ">=", "value" => "2023-11-22"}], "order_by" => ["inserted_at"], "order_directions" => ["desc"]}}
```

Here's my `handle_params`:

```
  @impl true
  def handle_params(params, _url, socket) do
    case NumberPorting.list_porting(params) do
      {:ok, {ports, meta}} ->
        {:noreply,
         socket
         |> assign(:meta, meta)
         |> stream(:porting_collection, ports, reset: true)
         |> apply_action(socket.assigns.live_action, params)}

      {:error, error} ->
        Logger.error("Error: #{inspect(error)}")
        {:noreply, push_navigate(socket, to: ~p"/porting")}
    end
  end
```

What am I doing wrong?

Thanks.

**Comment by ghenry** [comment]
Ah, I see it in the docs now "Date and Time Filters". Closing.

**Comment by ghenry** [comment]
Actually, I'm struggling to understand this:

https://hexdocs.pm/flop_phoenix/Flop.Phoenix.html#to_query/2

Does anyone have any examples for filtering a utc_datetime ecto col?

Thanks.

**Comment by woylie** [comment]
The part of the documentation you linked is not relevant here. In the error message, the filter looks like this:

```elixir
%{
  "field" => "customer_request_date",
  "op" => ">=",
  "value" => "2023-11-22"
}
```

So everything looks good on the flop_phoenix side.

The issue is that there is a mismatch between the type of the filter and the type in your Ecto schema. Flop tries to cast the filter value using the type in the schema, but `"2023-11-22"` cannot be cast as a `utc_datetime`.

```elixir
iex> Ecto.Type.cast(:utc_datetime, "2023-11-22")
:error
```

There are multiple ways to approach this.

You can update the filter value to `"2023-11-22 00:00:00"` before you pass the parameters to Flop, probably in the `handle_params` function. [Flop.Filter.pop/3](https://hexdocs.pm/flop/Flop.Filter.html#pop/3) might be useful here. You will also need to make sure that your input component sets the `value` attribute to a date string instead of a datetime string if the type is `"date"`.

You can also define a custom Ecto type that is able to cast a date string as a DateTime, but you would still need to update your `input` component as described in the first solution.

Finally, you can use a [custom field](https://hexdocs.pm/flop/Flop.Schema.html#module-custom-fields), set the `ecto_type` to `:date`, and convert the Date into a DateTime in the custom field function.

**Comment by woylie** [comment]
There's a new `Flop.Filter.update_value/3` function in the Flop main branch. You can do this now:

```elixir
  @impl true
  def handle_params(params, _url, socket) do
    params = prepare_params(params)

    case NumberPorting.list_porting(params) do
      {:ok, {ports, meta}} ->
        {:noreply,
         socket
         |> assign(:meta, meta)
         |> stream(:porting_collection, ports, reset: true)
         |> apply_action(socket.assigns.live_action, params)}

      {:error, error} ->
        Logger.error("Error: #{inspect(error)}")
        {:noreply, push_navigate(socket, to: ~p"/porting")}
    end
  end

  defp prepare_params(params) do
    Map.update(
      params,
      "filters",
      [],
      &Flop.Filter.update_value(&1, :customer_request_date, fn
        nil -> nil
        date -> date <> " 00:00:00"
      end)
    )
  end
```

**Comment by ghenry** [comment]
Thanks @woylie for your kind help, much appreciated! I'll go for the option of adding the time manually until you do another release.

In the meantime I'll send a few more coffees your way (using this for a private provisioning and number porting portal at SureVoIP with lots of Oban workers and LiveView).

Gavin.

**Comment by ghenry** [comment]
> There's a new `Flop.Filter.update_value/3` function in the Flop main branch. You can do this now:

Hmmm, I can't see that function?

https://github.com/search?q=repo%3Awoylie%2Fflop_phoenix%20update_value&type=code

**Comment by woylie** [comment]
> > There's a new `Flop.Filter.update_value/3` function in the Flop main branch. You can do this now:
> 
> Hmmm, I can't see that function?
> 
> https://github.com/search?q=repo%3Awoylie%2Fflop_phoenix%20update_value&type=code

It's in Flop: https://github.com/woylie/flop/blob/main/lib/flop/filter.ex#L1690

**Comment by ghenry** [comment]
Cool, that's working after doing:

```
mix deps.get
mix deps.unlock ecto_sql
mix deps.unlock ecto
```

and 

```
      {:flop, git: "https://github.com/woylie/flop.git", ref: "4b907a0", override: true},
      {:flop_phoenix, "~> 0.22.4"},
```

**Comment by ghenry** [comment]
Now I just need to figure out how to set a default value for the date field widget to today. If you don't pick anything, ie filtering by something else the date is obviously empty.

**Comment by woylie** [comment]
You would need to set default filter values before you make the query, so again in `handle_params`. Something like:

```elixir
  defp prepare_params(%{"filters" => filters} = params) do
    filters =
      Flop.Filter.update_value(filters, :customer_request_date, fn
        nil ->
          # if you want to override a removed date filter
          DateTime.new!(Date.utc_today(), ~T[00:00:00])
        date ->
          date <> " 00:00:00"
      end)

    %{params | "filters" => filters}
  end

  # To set a default when no filters were submitted yet
  defp prepare_params(%{} = params) do
    today = DateTime.new!(Date.utc_today(), ~T[00:00:00])
    Map.put(params, "filters", [%{"field" => "customer_request_date", "op" => ">=", "value" => today])
  end
```

**Comment by ghenry** [comment]
Thanks again!

I've normally been handling this in my ecto queries, but filters are new to me.

**Comment by ghenry** [comment]
That's working. I just have to set a default when there are some filters,
but no date picked. Leave with me.

**Comment by ghenry** [comment]
Just for others (or myself coming back), I check if date is not set:

```
  defp prepare_params(%{"filters" => filters} = params) do
    filters =
      Flop.Filter.update_value(filters, :customer_request_date, fn
        nil ->
          # if you want to override a removed date filter
          DateTime.new!(Date.utc_today(), ~T[00:00:00])

        date ->
          if date == "" do
            DateTime.new!(Date.utc_today(), ~T[00:00:00])
          else
            date <> " 00:00:00"
          end
      end)

    %{params | "filters" => filters}
  end
```

**Comment by ghenry** [comment]
Actually, is a "date" filter field is empty, should it even make it through and to the DB search?

**Comment by woylie** [comment]
Sorry, empty inputs produce `""`, not `nil`. I updated my examples above.

**Comment by woylie** [comment]
> P.S. How did you get colors on your Elixir code here?

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by ghenry** [comment]
> You would need to set default filter values before you make the query, so again in `handle_params`. Something like:
> 
> ```elixir
>   defp prepare_params(%{"filters" => filters} = params) do
>     filters =
>       Flop.Filter.update_value(filters, :customer_request_date, fn
>         "" ->
>           # if you want to override a removed date filter
>           DateTime.new!(Date.utc_today(), ~T[00:00:00])
>         date ->
>           date <> " 00:00:00"
>       end)
> 

When I get the date through as a param, we're now making:

`value" => "2023-11-30 00:00:00Z 00:00:00"}`

so I can either test as a string for a time suffix or something nicer. What's a nice way to do this match?

**Comment by woylie** [comment]
> so I can either test as a string for a time suffix or something nicer. What's a nice way to do this match?

You can check whether the string length exceeds 8. Not sure why the date input is producing a datetime string, though. Did you update your `input` component to convert the datetime values to date strings? The value for date inputs must be a date string, if you set it to a datetime string, you may get unexpected results in some browsers.

**Comment by woylie** [comment]
> I ended up testing if > 10. We set a default filter, so after the first render, clicking next on paging automatically adds another 00:00:00

I see, so it's not the filter, but the pagination and table components.

**Comment by woylie** [comment]
I assume this is resolved. Feel free to open a discussion if you have any more questions.
