### ISSUE TITLE
Filter-params example broken

### ISSUE THREAD

**Issue by rlopzc** [woylie/flop_phoenix#305]
**Is your feature request related to a problem? Please describe.**
I'm following the example to render filters. The issue is on the `handle_event("update_filter")`.

**Describe the solution you'd like**
For filters to work when following the examples.

**Describe alternatives you've considered**

**Additional context**
LiveView:
```elixir
  @impl Phoenix.LiveView
  def handle_event("update-filter", params, socket) do
    params = Map.delete(params, "_target")
    {:noreply, push_patch(socket, to: ~p"/files#{params}")}
  end
```

LiveView HTML
```elixir
<.filter_form
  fields={[:attachment, :type, :inserted_at]}
  meta={@meta}
  id="file-filter-form"
/>
```

Error
```
[error] GenServer #PID<0.2082.0> terminating
** (ArgumentError) maps cannot be converted to_param. A struct was expected, got: %{"filters" => %{"0" => %{"field" => "attachment", "value" => "da"}, "1" => %{"field" => "type", "value" => ""}, "2" => %{"field" => "inserted_at", "value" => ""}}, "order_by" => ["inserted_at"], "order_directions" => ["asc"]}
    (phoenix 1.7.10) lib/phoenix/param.ex:81: Phoenix.Param.Map.to_param/1
```

**Comment by woylie** [comment]
> ```elixir
>   @impl Phoenix.LiveView
>   def handle_event("update-filter", params, socket) do
>     params = Map.delete(params, "_target")
>     {:noreply, push_patch(socket, to: ~p"/files#{params}")}
>   end
> ```

It looks like you're missing a question mark there: `~p"/files?#{params}"`.

PS: Just fixed my bug report template.

**Comment by rlopzc** [comment]
Oh right, let me try with that 🤦
