### ISSUE TITLE
[Bug] Get Page Link Range incorrect when hitting the maximum

### ISSUE THREAD

**Issue by dbsimmons64** [woylie/flop_phoenix#322]
### Summary

I believe the calculation for get page link range is incorrect.

### Steps to reproduce

1. Use the Flop.Phoenix.pagination component with {:ellipsis, 3}
2. Select the last page, in my case this was 20
3. Pagination component dispaly 18, 19, 20
4. Select 18 and page 18 is display but Pagination component still display 18,19,20 meaning you cannot select page 17.

### Expected behaviour

I would expect that when I select page 18 I'd see 17,18,19.

### Actual behaviour

Unable to select page 17 from pagination component.

### Elixir/Erlang version

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

### Flop and Ecto versions

* ecto 3.11.1 (Hex package) (mix)
* ecto_sql 3.11.1 (Hex package) (mix)
  locked at 3.11.1 (ecto_sql) ce14063a
* flop 0.25.0 (Hex package) (mix)
  locked at 0.25.0 (flop) 7e4b01b7
* flop_phoenix 0.22.6 (Hex package) (mix)
  locked at 0.22.6 (flop_phoenix) 0db1677f

### Additional context

I believe the `get_page_link_range` function is incorrect:
```        
     current_page + additional >= total_pages ->
```
should be:
```
      current_page + additional > total_pages ->
```

**Comment by woylie** [comment]
Thanks for opening the issue, this should be fixed on main.

**Comment by dbsimmons64** [comment]
Great stuff - thanks for creating a fantastic library.
