### ISSUE TITLE
How can I style my table and missing filter_fields

### ISSUE THREAD

**Issue by herrnesto** [woylie/flop_phoenix#367]
Hello, how can I style my table, i.e. pagination? Is the idea to do this through core_components as page_size_link? But how I need to write that?

**Comment by woylie** [comment]
I'm not sure I understand the question. The components use default CSS classes that can be overridden, as described [here](https://hexdocs.pm/flop_phoenix/Flop.Phoenix.html#module-customization). To style the components, you just write CSS styles for those classes, or set utility classes (e.g. Tailwind) in the options.

**Comment by herrnesto** [comment]
I'm sorry, I somehow missed this page... But one question still remains. I added the `filter_form` as in the documentation. But it complains that `filter_fields` is missing. Is there also an example how this must look like? I don't find it...
```
  def filter_form(%{meta: meta} = assigns) do
    assigns = assign(assigns, form: Phoenix.Component.to_form(meta), meta: nil)

    ~H"""
    <.form for={@form} id={@id} phx-target={@target} phx-change={@on_change} phx-submit={@on_change}>
      <.filter_fields :let={i} form={@form} fields={@fields}>
        <.input field={i.field} label={i.label} type={i.type} phx-debounce={120} {i.rest} />
      </.filter_fields>

      <button class="button" name="reset">reset</button>
    </.form>
    """
  end
```

**Comment by herrnesto** [comment]
Ah ok, i need to import `Flop.Phoenix` into `CoreComponents`. Now it renders the filter
