### ISSUE TITLE
Enable flop_phoenix for use with DBs outside the Ecto ecosystem

### ISSUE THREAD

**Issue by kuatroka** [woylie/flop_phoenix#383]
**Is your feature request related to a problem? Please describe.**
There are certain DBs or ways of dealing with data to be presented in a table format or in search/filter/typeahead scenario that are better or faster than Postgres or SQLite. 
Two of these options are columns oriented, embedded and very fast **Duckdb** and parquet file format. Both can be used with libraries like **duckdbex** and parquet with **explorer**. Both options are a single file .db or single file .parquet that use columnar structure making them exceptionally fast for analytics or table / autocomplete use cases.

**Describe the solution you'd like**
Enable flop_phoenix and flop to integrate with **duckdb** and/or **explorer** without Ecto since they are not supported by Ecto.

**Describe alternatives you've considered**
The alternative is to keep using SQLite or Postgres though with slower response times.

**Additional context**
Adding sample very raw  project that used both approaches for a simple table and pagination example using built-in Phoenix CoreComponents.
[pento](https://github.com/kuatroka/pento)
When installed use the tabs selected in the gif
![image](https://github.com/user-attachments/assets/9e0e16b2-84c8-419d-b4a1-0146c0cf2be1)

**Comment by woylie** [comment]
Thank you for the feature request. Support for other adapters than Ecto is already in progress and tracked here: https://github.com/woylie/flop/issues/238.

Internally, Flop already uses an [adapter behaviour](https://github.com/woylie/flop/blob/main/lib/flop/adapter.ex) which is implemented by an [Ecto adapter](https://github.com/woylie/flop/blob/main/lib/flop/adapter/ecto.ex). Note that the behaviour is still undocumented and the API is not finalized yet.

Closing this in favor of https://github.com/woylie/flop/issues/238.
