### ISSUE TITLE
Add support for phoenix_html 3.0.0

### ISSUE THREAD

**Issue by jesse-iluminai** [woylie/flop_phoenix#41]
**Describe the bug**
phoenix_html 3.0.0 was recently (like very recently) released and flop_phoenix is pegged to `~> 2.14` which is preventing us from updating.

**To Reproduce**
Specify phoenix_html to 3.0.0 in your mix file as well as flop_phoenix 0.7.0

**Expected behavior**
Can update :)

**Versions:**
 - Flop.Phoenix: 0.7.0
 - Flop: 0.11.0
 - Elixir: 1.12.0
 - Erlang: 24
 - Phoenix.HTML: 3.0.0
 - Phoenix.LiveView: 0.16.0
 - Ecto: 
 - Ecto SQL:

**Comment by woylie** [comment]
Support for phoenix_html 3.0 and phoenix_live_view 0.16.0 has already been merged to master.

**Comment by jesse-iluminai** [comment]
Awesome. Do you plan on publishing a new version soon?
